kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    ctl-app: web-module
  name: web-module
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      ctl-app: web-module
  template:
    metadata:
      labels:
        ctl-app: web-module
    spec:
      containers:
      - name: web-module
        image: {{ .Env.DockerImageName }}
        env:
        - name: SPRING_CLOUD_CONFIG_ENABLED
          value: "true"
        - name: SPRING_CLOUD_CONSUL_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: SPRING_CLOUD_CONSUL_TOKEN
          value: "e9138d5b-c037-e88b-5cea-a381ae7be43e"
        ports:
        - containerPort: 80
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /ui/module/index.html
            port: 80
          initialDelaySeconds: 30
          timeoutSeconds: 30
      imagePullSecrets:
      - name: regcred
